#ifndef ORDERCOUNTMODEL_GLOBAL_H
#define ORDERCOUNTMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ORDERCOUNTMODEL_LIBRARY)
#  define ORDERCOUNTMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ORDERCOUNTMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ORDERCOUNTMODEL_GLOBAL_H
